# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MyLibrary
version:      3.0.3
version_from: lib/MyLibrary/Core.pm
installdirs:  site
requires:
    Carp:                          0
    CGI::Session:                  0
    DBI:                           1.43
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
